### ISSUE TITLE
Use of RIOT API KEY

### ISSUE THREAD

**Issue by Sattishh** [haysberg/kayo#6]
Hiya, this isn't an issue post but I was just generally curious where and how the RIOT API Key is used.

Thanks

**Comment by haysberg** [comment]
Hello,

It is not in use anymore.
The previous version of the bot used an API key from the Riot Schedule web page which was the source of the data. 

It caused many problems :

- the fact that the matches were not updated when they had to start in advance (say, if the first BO3 was fast and the 2nd match of the night starts half an hour early)
- some matches just didn't appear at all in the database (for example, GC matches before the final stage were never put on the schedule)

After completely reworking the bot, it now uses vlr.gg as a source, so the bot doesn't need the API key anymore.

**Comment by Sattishh** [comment]
Ahh okay noted, thanks for the clarification!! I was planning to use VLR.GG for analytics visualization so I was exploring this repository.
